apiVersion: v1
kind: Service
metadata:
  name: {{ include "fossology.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}-web
{{ include "fossology.labels" . | indent 4 }}
spec:
  type: NodePort # {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
